/// Cross-language compatibility tests.
///
/// Test vectors were generated by running the Python mediaflow-proxy
/// EncryptionHandler and encode_mediaflow_proxy_url with a fixed IV
/// (bytes 0x00..0x0f) and the password "test_secret".
///
/// Run:  cargo test --test compat_tests
use mediaflow_proxy_light::auth::encryption::{EncryptionHandler, ProxyData};
use std::collections::HashMap;

const PASSWORD: &[u8] = b"test_secret";

// ────────────────────────────────────────────────────────────────────────────
// Helpers
// ────────────────────────────────────────────────────────────────────────────

fn handler() -> EncryptionHandler {
    EncryptionHandler::new(PASSWORD).unwrap()
}

/// Extract the token from a `/_token_{token}/…` or `?token={token}` URL.
fn extract_token_from_url(url: &str) -> &str {
    if let Some(rest) = url.strip_prefix("https://proxy.example.com/_token_") {
        let end = rest.find('/').unwrap_or(rest.len());
        &rest[..end]
    } else if let Some(pos) = url.find("?token=") {
        &url[pos + 7..]
    } else {
        panic!("no token found in URL: {url}");
    }
}

/// Parse `key=value` pairs from a URL query string (percent-decoded, `+`→space).
fn parse_qs(url: &str) -> HashMap<String, String> {
    let qs = url.split_once('?').map(|(_, q)| q).unwrap_or("");
    qs.split('&')
        .filter(|p| !p.is_empty())
        .filter_map(|p| p.split_once('='))
        .map(|(k, v)| {
            let decode = |s: &str| {
                urlencoding::decode(s)
                    .unwrap_or_else(|_| s.into())
                    .replace('+', " ")
            };
            (decode(k), decode(v))
        })
        .collect()
}

// ────────────────────────────────────────────────────────────────────────────
// 1. Python flat-dict token decryption
// ────────────────────────────────────────────────────────────────────────────

/// Python generated: encrypt_data({"d": "https://cdn.example.com/stream.m3u8"})
#[test]
fn decrypt_python_token_destination_only() {
    let tok =
        "AAECAwQFBgcICQoLDA0OD1NDNLU6BmO_093POOmfhHoL29QQVC_7Zf3ZkxMIV0AmCCVw7DPCWWcA59PdeoN7PQ";
    let pd = handler().decrypt(tok, None).unwrap();
    assert_eq!(pd.destination, "https://cdn.example.com/stream.m3u8");
    // No headers should be present (empty flat dict)
    let req_headers_empty = pd
        .request_headers
        .as_ref()
        .and_then(|v| v.as_object())
        .map(|o| o.is_empty())
        .unwrap_or(true);
    assert!(req_headers_empty, "expected no request headers");
}

/// Python generated: encrypt_data({"d": dest, "h_Authorization": "Bearer abc123",
///                                  "r_Content-Type": "video/mp2t"})
#[test]
fn decrypt_python_token_with_headers() {
    let tok = "AAECAwQFBgcICQoLDA0OD1NDNLU6BmO_093POOmfhHrso34lg6G0chROcdZKj39R67pjzjuqtC517wNInGILxeXlAhDSft4HnKp-LfKKD1A_LkwUZtJbLCnbaOu91O7jmmI1peWOfBG-rKaNLnw_8rrCCOwpjG-wQV-RfqxOmSA";
    let pd = handler().decrypt(tok, None).unwrap();
    assert_eq!(pd.destination, "https://cdn.example.com/video.ts");

    let req_hdrs = pd.request_headers.as_ref().unwrap().as_object().unwrap();
    assert_eq!(req_hdrs["Authorization"].as_str().unwrap(), "Bearer abc123");

    let resp_hdrs = pd.response_headers.as_ref().unwrap().as_object().unwrap();
    assert_eq!(resp_hdrs["Content-Type"].as_str().unwrap(), "video/mp2t");
}

/// Python generated token containing "exp": 9999999999 (far future — valid).
#[test]
fn decrypt_python_token_future_expiry_accepted() {
    let tok = "AAECAwQFBgcICQoLDA0OD1NDNLU6BmO_093POOmfhHrso34lg6G0chROcdZKj39R67pjzjuqtC517wNInGILxeXlAhDSft4HnKp-LfKKD1A_LkwUZtJbLCnbaOu91O7jmmI1peWOfBG-rKaNLnw_8uNPK45zAE-ieTloDrDTd1y0y6opdZfJctp1H0gH56AmWLjK5iEZ_8wyQhswIlUszA";
    // exp=9999999999 is far in the future — should succeed
    let pd = handler().decrypt(tok, None).unwrap();
    assert_eq!(pd.destination, "https://cdn.example.com/video.ts");
    assert!(pd.exp.is_some());
    assert!(pd.exp.unwrap() > 9_000_000_000);
}

/// Python generated token containing "exp": 1 (past — expired).
#[test]
fn decrypt_python_token_expired_rejected() {
    let tok = "AAECAwQFBgcICQoLDA0OD1NDNLU6BmO_093POOmfhHoL29QQVC_7Zf3ZkxMIV0AmucQT8Vs8wdNNyk1hI5uuUBy8Rc_a5QvjY1eU-Bls4YU";
    let result = handler().decrypt(tok, None);
    assert!(result.is_err(), "expired token must be rejected");
    let msg = format!("{:?}", result.unwrap_err());
    assert!(
        msg.contains("expired"),
        "error should mention expiry, got: {msg}"
    );
}

/// Python generated token containing "ip": "1.2.3.4" — matching IP accepted.
#[test]
fn decrypt_python_token_ip_match_accepted() {
    let tok = "AAECAwQFBgcICQoLDA0OD1NDNLU6BmO_093POOmfhHoL29QQVC_7Zf3ZkxMIV0AmfW_t2Tn56K1A199r-ROvg3cmPtF_-uc3fDeeJ2LbZG0";
    let pd = handler().decrypt(tok, Some("1.2.3.4")).unwrap();
    assert_eq!(pd.destination, "https://cdn.example.com/stream.m3u8");
}

/// Same token but wrong IP → rejected.
#[test]
fn decrypt_python_token_ip_mismatch_rejected() {
    let tok = "AAECAwQFBgcICQoLDA0OD1NDNLU6BmO_093POOmfhHoL29QQVC_7Zf3ZkxMIV0AmfW_t2Tn56K1A199r-ROvg3cmPtF_-uc3fDeeJ2LbZG0";
    let result = handler().decrypt(tok, Some("9.9.9.9"));
    assert!(result.is_err(), "IP mismatch must be rejected");
}

/// Rust-generated (ProxyData) tokens are still accepted.
#[test]
fn decrypt_rust_proxydata_token_still_works() {
    let h = handler();
    let original = ProxyData {
        destination: "https://cdn.example.com/stream.m3u8".into(),
        query_params: Some(serde_json::json!({"key": "val"})),
        request_headers: Some(serde_json::json!({"Authorization": "Bearer tok"})),
        response_headers: None,
        exp: None,
        ip: None,
    };
    let token = h.encrypt(&original).unwrap();
    let decoded = h.decrypt(&token, None).unwrap();
    assert_eq!(decoded.destination, original.destination);
    let req_hdrs = decoded.request_headers.unwrap();
    assert_eq!(req_hdrs["Authorization"].as_str().unwrap(), "Bearer tok");
}

// ────────────────────────────────────────────────────────────────────────────
// 2. URL generation — encrypted (/_token_ path format)
// ────────────────────────────────────────────────────────────────────────────

use mediaflow_proxy_light::proxy::handler::build_proxy_url;

fn default_headers() -> HashMap<String, String> {
    HashMap::new()
}

/// Encrypted URL must use Python's /_token_{token}{endpoint} path format.
#[test]
fn encrypted_url_uses_token_path_format() {
    let url = build_proxy_url(
        "https://proxy.example.com",
        Some("/proxy/stream"),
        "https://cdn.example.com/stream.m3u8",
        &default_headers(),
        &default_headers(),
        &default_headers(),
        &default_headers(),
        &[],
        None,
        None,
        Some("test_secret"),
        None,
        None,
        false,
    )
    .unwrap();

    assert!(
        url.starts_with("https://proxy.example.com/_token_"),
        "encrypted URL must use /_token_ prefix, got: {url}"
    );
    assert!(
        url.ends_with("/proxy/stream"),
        "endpoint must follow token, got: {url}"
    );
    // Must NOT contain ?token=
    assert!(
        !url.contains("?token="),
        "must not use query-param token style"
    );
}

/// The token embedded in the /_token_ URL must be decryptable back to the original payload.
#[test]
fn encrypted_url_token_is_valid_and_decryptable() {
    let dest = "https://cdn.example.com/stream.m3u8";
    let mut req_hdrs = HashMap::new();
    req_hdrs.insert("Authorization".into(), "Bearer tok".into());

    let url = build_proxy_url(
        "https://proxy.example.com",
        Some("/proxy/stream"),
        dest,
        &default_headers(),
        &req_hdrs,
        &default_headers(),
        &default_headers(),
        &[],
        None,
        None,
        Some("test_secret"),
        None,
        None,
        false,
    )
    .unwrap();

    let token = extract_token_from_url(&url);
    let pd = handler().decrypt(token, None).unwrap();
    assert_eq!(pd.destination, dest);
    let rh = pd.request_headers.unwrap();
    assert_eq!(rh["Authorization"].as_str().unwrap(), "Bearer tok");
}

/// Filename is appended after the endpoint path, not before the token.
#[test]
fn encrypted_url_filename_after_endpoint() {
    let url = build_proxy_url(
        "https://proxy.example.com",
        Some("/proxy/stream"),
        "https://cdn.example.com/stream.m3u8",
        &default_headers(),
        &default_headers(),
        &default_headers(),
        &default_headers(),
        &[],
        None,
        Some("video.m3u8"),
        Some("test_secret"),
        None,
        None,
        false,
    )
    .unwrap();

    // Format: https://proxy.example.com/_token_{tok}/proxy/stream/video.m3u8
    assert!(url.ends_with("/proxy/stream/video.m3u8"), "got: {url}");
    let token = extract_token_from_url(&url);
    // token must still decrypt correctly (filename is NOT in the token)
    let pd = handler().decrypt(token, None).unwrap();
    assert_eq!(pd.destination, "https://cdn.example.com/stream.m3u8");
}

/// Expiration is embedded in the token and honoured on decrypt.
#[test]
fn encrypted_url_expiration_in_token() {
    let url = build_proxy_url(
        "https://proxy.example.com",
        Some("/proxy/stream"),
        "https://cdn.example.com/stream.m3u8",
        &default_headers(),
        &default_headers(),
        &default_headers(),
        &default_headers(),
        &[],
        None,
        None,
        Some("test_secret"),
        Some(3600), // 1 hour from now
        None,
        false,
    )
    .unwrap();

    let token = extract_token_from_url(&url);
    let pd = handler().decrypt(token, None).unwrap();
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_secs();
    let exp = pd.exp.unwrap();
    assert!(exp > now, "exp {exp} must be in the future (now={now})");
    assert!(exp <= now + 3601, "exp must be ~1 hour from now");
}

/// IP binding: token carries the ip and middleware enforces it.
#[test]
fn encrypted_url_ip_binding_in_token() {
    let url = build_proxy_url(
        "https://proxy.example.com",
        Some("/proxy/stream"),
        "https://cdn.example.com/stream.m3u8",
        &default_headers(),
        &default_headers(),
        &default_headers(),
        &default_headers(),
        &[],
        None,
        None,
        Some("test_secret"),
        None,
        Some("1.2.3.4"),
        false,
    )
    .unwrap();

    let token = extract_token_from_url(&url);
    assert!(handler().decrypt(token, Some("1.2.3.4")).is_ok());
    assert!(handler().decrypt(token, Some("9.9.9.9")).is_err());
}

// ────────────────────────────────────────────────────────────────────────────
// 3. URL generation — unencrypted (flat query params)
// ────────────────────────────────────────────────────────────────────────────

/// Unencrypted URL must use ?d=... query param style (no /_token_).
#[test]
fn unencrypted_url_uses_query_param_style() {
    let url = build_proxy_url(
        "https://proxy.example.com",
        Some("/proxy/stream"),
        "https://cdn.example.com/stream.m3u8",
        &default_headers(),
        &default_headers(),
        &default_headers(),
        &default_headers(),
        &[],
        None,
        None,
        None, // no api_password
        None,
        None,
        false,
    )
    .unwrap();

    assert!(
        url.starts_with("https://proxy.example.com/proxy/stream?"),
        "got: {url}"
    );
    assert!(!url.contains("/_token_"), "must not use token path format");
    let qs = parse_qs(&url);
    assert_eq!(qs["d"], "https://cdn.example.com/stream.m3u8");
}

/// Request headers get h_ prefix; response headers get r_ prefix.
#[test]
fn unencrypted_url_header_prefixes() {
    let mut req_hdrs = HashMap::new();
    req_hdrs.insert("Authorization".into(), "Bearer tok".into());
    let mut resp_hdrs = HashMap::new();
    resp_hdrs.insert("Content-Type".into(), "video/mp4".into());

    let url = build_proxy_url(
        "https://proxy.example.com",
        Some("/proxy/stream"),
        "https://cdn.example.com/stream.m3u8",
        &default_headers(),
        &req_hdrs,
        &resp_hdrs,
        &default_headers(),
        &[],
        None,
        None,
        None,
        None,
        None,
        false,
    )
    .unwrap();

    let qs = parse_qs(&url);
    assert_eq!(
        qs["h_Authorization"], "Bearer tok",
        "request header needs h_ prefix"
    );
    assert_eq!(
        qs["r_Content-Type"], "video/mp4",
        "response header needs r_ prefix"
    );
}

/// range and if-range request headers must be excluded (they are per-request dynamic values).
/// Python does the same: SUPPORTED_REQUEST_HEADERS are filtered out.
#[test]
fn unencrypted_url_skips_supported_request_headers() {
    let mut req_hdrs = HashMap::new();
    req_hdrs.insert("Authorization".into(), "Bearer tok".into());
    req_hdrs.insert("range".into(), "bytes=0-".into()); // must be excluded
    req_hdrs.insert("if-range".into(), "etag123".into()); // must be excluded

    let url = build_proxy_url(
        "https://proxy.example.com",
        Some("/proxy/stream"),
        "https://cdn.example.com/stream.m3u8",
        &default_headers(),
        &req_hdrs,
        &default_headers(),
        &default_headers(),
        &[],
        None,
        None,
        None,
        None,
        None,
        false,
    )
    .unwrap();

    let qs = parse_qs(&url);
    assert!(
        qs.contains_key("h_Authorization"),
        "Authorization must be present"
    );
    assert!(!qs.contains_key("h_range"), "range must be filtered out");
    assert!(
        !qs.contains_key("h_if-range"),
        "if-range must be filtered out"
    );
    assert!(
        !qs.contains_key("range"),
        "range must not appear without prefix either"
    );
}

/// Propagate headers get rp_ prefix.
#[test]
fn unencrypted_url_propagate_headers_rp_prefix() {
    let mut prop = HashMap::new();
    prop.insert("Cache-Control".into(), "no-cache".into());

    let url = build_proxy_url(
        "https://proxy.example.com",
        Some("/proxy/stream"),
        "https://cdn.example.com/stream.m3u8",
        &default_headers(),
        &default_headers(),
        &default_headers(),
        &prop,
        &[],
        None,
        None,
        None,
        None,
        None,
        false,
    )
    .unwrap();

    let qs = parse_qs(&url);
    assert_eq!(
        qs["rp_Cache-Control"], "no-cache",
        "propagate header needs rp_ prefix"
    );
}

/// remove_response_headers serialises as x_headers=A,B.
#[test]
fn unencrypted_url_remove_headers_x_headers_param() {
    let url = build_proxy_url(
        "https://proxy.example.com",
        Some("/proxy/stream"),
        "https://cdn.example.com/stream.m3u8",
        &default_headers(),
        &default_headers(),
        &default_headers(),
        &default_headers(),
        &["X-Frame-Options".into(), "X-XSS-Protection".into()],
        None,
        None,
        None,
        None,
        None,
        false,
    )
    .unwrap();

    let qs = parse_qs(&url);
    let x = qs["x_headers"].as_str();
    // Order from Vec<String> is deterministic (insertion order)
    assert!(
        x.contains("X-Frame-Options") && x.contains("X-XSS-Protection"),
        "x_headers must list both headers, got: {x}"
    );
}

/// stream_transformer serialises as transformer=<id>.
#[test]
fn unencrypted_url_stream_transformer_param() {
    let url = build_proxy_url(
        "https://proxy.example.com",
        Some("/proxy/stream"),
        "https://cdn.example.com/stream.m3u8",
        &default_headers(),
        &default_headers(),
        &default_headers(),
        &default_headers(),
        &[],
        Some("tsfix"),
        None,
        None,
        None,
        None,
        false,
    )
    .unwrap();

    let qs = parse_qs(&url);
    assert_eq!(qs["transformer"], "tsfix");
}

/// filename is appended to the path before the query string (like Python).
#[test]
fn unencrypted_url_filename_in_path() {
    let url = build_proxy_url(
        "https://proxy.example.com",
        Some("/proxy/stream"),
        "https://cdn.example.com/stream.m3u8",
        &default_headers(),
        &default_headers(),
        &default_headers(),
        &default_headers(),
        &[],
        None,
        Some("video.m3u8"),
        None,
        None,
        None,
        false,
    )
    .unwrap();

    // Path must include filename before the ?
    let path = url.split('?').next().unwrap();
    assert!(
        path.ends_with("/proxy/stream/video.m3u8"),
        "filename must be appended to path, got path: {path}"
    );
    // d= must still be in query string
    let qs = parse_qs(&url);
    assert!(qs.contains_key("d"));
}

// ────────────────────────────────────────────────────────────────────────────
// 4. Python payload structure — from_python_flat_dict
// ────────────────────────────────────────────────────────────────────────────

#[test]
fn from_python_flat_dict_maps_destination() {
    let map: serde_json::Map<String, serde_json::Value> =
        serde_json::from_str(r#"{"d": "https://cdn.example.com/stream.m3u8"}"#).unwrap();
    let pd = ProxyData::from_python_flat_dict(map);
    assert_eq!(pd.destination, "https://cdn.example.com/stream.m3u8");
    assert!(
        pd.request_headers.is_none()
            || pd
                .request_headers
                .as_ref()
                .unwrap()
                .as_object()
                .unwrap()
                .is_empty()
    );
}

#[test]
fn from_python_flat_dict_splits_prefixed_headers() {
    let map: serde_json::Map<String, serde_json::Value> = serde_json::from_str(
        r#"{"d": "https://cdn.example.com/video.ts",
            "h_Authorization": "Bearer abc",
            "r_Content-Type": "video/mp2t",
            "extra_param": "value"}"#,
    )
    .unwrap();
    let pd = ProxyData::from_python_flat_dict(map);
    assert_eq!(pd.destination, "https://cdn.example.com/video.ts");

    let req = pd.request_headers.unwrap();
    assert_eq!(req["Authorization"].as_str().unwrap(), "Bearer abc");

    let resp = pd.response_headers.unwrap();
    assert_eq!(resp["Content-Type"].as_str().unwrap(), "video/mp2t");

    // Non-prefixed extra params end up in query_params
    let qp = pd.query_params.unwrap();
    assert_eq!(qp["extra_param"].as_str().unwrap(), "value");
}

#[test]
fn from_python_flat_dict_strips_exp_and_ip_from_params() {
    let map: serde_json::Map<String, serde_json::Value> = serde_json::from_str(
        r#"{"d": "https://cdn.example.com/stream.m3u8",
            "exp": 9999999999,
            "ip": "1.2.3.4"}"#,
    )
    .unwrap();
    let pd = ProxyData::from_python_flat_dict(map);
    assert_eq!(pd.exp, Some(9_999_999_999));
    assert_eq!(pd.ip.as_deref(), Some("1.2.3.4"));
    // exp and ip must NOT appear in query_params
    assert!(
        pd.query_params.is_none()
            || pd
                .query_params
                .as_ref()
                .unwrap()
                .as_object()
                .unwrap()
                .is_empty(),
        "exp/ip should not appear in query_params"
    );
}

// ────────────────────────────────────────────────────────────────────────────
// 5. Middleware /_token_ path extraction — via actix-web test client
//
// Notes on test strategy:
//  a) `test::call_service` panics if the service returns `Err(...)`.  Auth
//     rejection currently propagates as an actix-web `Error` (which the real
//     HTTP dispatcher converts to a 401 response via `ResponseError`).  To
//     test rejection without panicking we use `test::try_call_service` —
//     which is unavailable in actix-web 4 — so rejection logic is instead
//     covered by direct `decrypt()` unit tests above.
//
//  b) actix-web's route matching reads the URI from `req.head().uri` at the
//     time the *router* service is called.  Because `AuthMiddleware::call`
//     rewrites `req.head_mut().uri` before forwarding to the inner service,
//     the router sees the stripped path.  We verify this with a
//     `default_service` echo handler rather than an exact-path route, which
//     avoids a dependency on actix-web's internal route-caching behaviour.
// ────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod middleware_tests {
    use actix_web::{test, web, App, HttpRequest, HttpResponse};
    use mediaflow_proxy_light::auth::encryption::{EncryptionHandler, ProxyData};
    use mediaflow_proxy_light::auth::middleware::AuthMiddleware;

    fn make_token(password: &str, dest: &str) -> String {
        let h = EncryptionHandler::new(password.as_bytes()).unwrap();
        let pd = ProxyData {
            destination: dest.into(),
            query_params: None,
            request_headers: None,
            response_headers: None,
            exp: None,
            ip: None,
        };
        h.encrypt(&pd).unwrap()
    }

    /// Returns 200 with the request path as body — lets us verify URI rewriting.
    async fn echo_path(req: HttpRequest) -> HttpResponse {
        HttpResponse::Ok().body(req.path().to_string())
    }

    // ── 5a. /_token_ path token: auth accepted, path rewritten ───────────────

    #[actix_web::test]
    async fn path_token_accepted() {
        let token = make_token("secret", "https://cdn.example.com/stream.m3u8");
        let app = test::init_service(
            App::new()
                .wrap(AuthMiddleware::new("secret".into()))
                .default_service(web::to(echo_path)),
        )
        .await;

        let req = test::TestRequest::get()
            .uri(&format!("/_token_{}/proxy/stream", token))
            .to_request();
        let resp = test::call_service(&app, req).await;
        assert_eq!(resp.status(), 200, "/_token_ path token must be accepted");
    }

    #[actix_web::test]
    async fn path_token_uri_is_rewritten_to_endpoint() {
        // After stripping /_token_{token}, the handler must see /proxy/stream.
        let token = make_token("secret", "https://cdn.example.com/stream.m3u8");
        let app = test::init_service(
            App::new()
                .wrap(AuthMiddleware::new("secret".into()))
                .default_service(web::to(echo_path)),
        )
        .await;

        let req = test::TestRequest::get()
            .uri(&format!("/_token_{}/proxy/stream", token))
            .to_request();
        let resp = test::call_service(&app, req).await;
        let body = test::read_body(resp).await;
        assert_eq!(
            body,
            "/proxy/stream",
            "middleware must strip /_token_ prefix; handler saw: {}",
            String::from_utf8_lossy(&body)
        );
    }

    #[actix_web::test]
    async fn path_token_with_filename_uri_rewritten() {
        let token = make_token("secret", "https://cdn.example.com/stream.m3u8");
        let app = test::init_service(
            App::new()
                .wrap(AuthMiddleware::new("secret".into()))
                .default_service(web::to(echo_path)),
        )
        .await;

        let req = test::TestRequest::get()
            .uri(&format!("/_token_{}/proxy/stream/video.m3u8", token))
            .to_request();
        let resp = test::call_service(&app, req).await;
        let body = test::read_body(resp).await;
        assert_eq!(
            body,
            "/proxy/stream/video.m3u8",
            "filename must be preserved after rewrite; handler saw: {}",
            String::from_utf8_lossy(&body)
        );
    }

    // ── 5b. ?token= query-param token still works ────────────────────────────

    #[actix_web::test]
    async fn query_token_accepted() {
        let token = make_token("secret", "https://cdn.example.com/stream.m3u8");
        let app = test::init_service(
            App::new()
                .wrap(AuthMiddleware::new("secret".into()))
                .default_service(web::to(echo_path)),
        )
        .await;

        let req = test::TestRequest::get()
            .uri(&format!("/proxy/stream?token={}", token))
            .to_request();
        let resp = test::call_service(&app, req).await;
        assert_eq!(resp.status(), 200, "?token= query param must be accepted");

        // Path must NOT be rewritten for query-param token style
        let body = test::read_body(resp).await;
        assert_eq!(body, "/proxy/stream");
    }

    // ── 5c. ?api_password= direct auth still works ───────────────────────────

    #[actix_web::test]
    async fn direct_api_password_accepted() {
        let app = test::init_service(
            App::new()
                .wrap(AuthMiddleware::new("secret".into()))
                .default_service(web::to(echo_path)),
        )
        .await;

        let req = test::TestRequest::get()
            .uri("/proxy/stream?api_password=secret&d=https://cdn.example.com/stream.m3u8")
            .to_request();
        let resp = test::call_service(&app, req).await;
        assert_eq!(resp.status(), 200, "?api_password= must be accepted");
    }

    // ── 5d. No password configured → allow everything ────────────────────────

    #[actix_web::test]
    async fn no_password_configured_allows_all() {
        let app = test::init_service(
            App::new()
                .wrap(AuthMiddleware::new("".into()))
                .default_service(web::to(echo_path)),
        )
        .await;

        let req = test::TestRequest::get()
            .uri("/proxy/stream?d=https://cdn.example.com/stream.m3u8")
            .to_request();
        let resp = test::call_service(&app, req).await;
        assert_eq!(resp.status(), 200, "no password → allow all");
    }

    // ── 5e. Auth rejection — tested via decrypt() unit tests (section 1 above)
    //        because test::call_service panics when the service returns Err.
    //        The real HTTP dispatcher converts the Err to a 401 response via
    //        AppError's ResponseError impl (see src/error.rs).

    /// Confirms that a wrong-password token is rejected at the decrypt layer.
    #[actix_web::test]
    async fn wrong_password_token_decrypt_rejected() {
        let good = EncryptionHandler::new(b"secret").unwrap();
        let bad = EncryptionHandler::new(b"wrong").unwrap();
        let pd = ProxyData {
            destination: "https://cdn.example.com/stream.m3u8".into(),
            query_params: None,
            request_headers: None,
            response_headers: None,
            exp: None,
            ip: None,
        };
        let token = bad.encrypt(&pd).unwrap();
        // The "secret" handler must reject a token produced by "wrong"
        assert!(
            good.decrypt(&token, None).is_err(),
            "wrong-password token must be rejected"
        );
    }

    /// Python flat-dict token is also rejected when the password doesn't match.
    #[actix_web::test]
    async fn python_token_wrong_password_rejected() {
        // Python token from section 1 (PASSWORD = "test_secret")
        let tok = "AAECAwQFBgcICQoLDA0OD1NDNLU6BmO_093POOmfhHoL29QQVC_7Zf3ZkxMIV0AmCCVw7DPCWWcA59PdeoN7PQ";
        let wrong = EncryptionHandler::new(b"wrong_password").unwrap();
        assert!(wrong.decrypt(tok, None).is_err());
    }
}
